[2024-03-14 01:53:54,321: INFO: main: Welcome Ali Mustaf Ali.]
[2024-03-14 03:01:29,500: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:01:29,679: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:01:29,681: INFO: common: created directory at: artifacts]
[2024-03-14 03:01:29,685: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-14 03:01:29,687: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1LrVMghN3dL4vK8RzTKQl_foCAOTtPrMW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 03:01:32,855: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1LrVMghN3dL4vK8RzTKQl_foCAOTtPrMW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 03:15:47,351: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-14 03:15:47,353: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 03:15:47,354: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 03:15:47,354: INFO: common: created directory at: artifacts]
[2024-03-14 03:15:47,355: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-14 03:15:47,356: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1LrVMghN3dL4vK8RzTKQl_foCAOTtPrMW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 03:15:50,491: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1LrVMghN3dL4vK8RzTKQl_foCAOTtPrMW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 03:15:50,515: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-14 15:21:30,350: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 15:21:30,505: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 15:21:30,556: INFO: common: created directory at: artifacts]
[2024-03-14 15:21:30,571: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 15:21:35,278: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 15:32:32,804: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-14 15:32:32,808: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 15:32:32,810: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 15:32:32,811: INFO: common: created directory at: artifacts]
[2024-03-14 15:32:32,812: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-14 15:32:32,812: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1LrVMghN3dL4vK8RzTKQl_foCAOTtPrMW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 15:32:36,238: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1LrVMghN3dL4vK8RzTKQl_foCAOTtPrMW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 15:32:36,361: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-14 15:32:36,361: INFO: main: *******************]
[2024-03-14 15:32:36,361: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 15:32:36,365: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 15:32:36,367: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 15:32:36,367: INFO: common: created directory at: artifacts]
[2024-03-14 15:32:36,368: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 15:32:37,093: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 15:32:37,562: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-14 16:16:23,217: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 16:16:23,225: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 16:16:23,230: INFO: common: created directory at: artifacts]
[2024-03-14 16:16:23,235: INFO: common: created directory at: artifacts\training]
[2024-03-14 16:23:23,750: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-14 16:23:23,761: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 16:23:23,764: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 16:23:23,765: INFO: common: created directory at: artifacts]
[2024-03-14 16:23:23,766: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-14 16:23:23,766: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 16:23:31,177: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 16:23:31,259: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-14 16:23:31,259: INFO: main: *******************]
[2024-03-14 16:23:31,259: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 16:23:31,264: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 16:23:31,268: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 16:23:31,268: INFO: common: created directory at: artifacts]
[2024-03-14 16:23:31,269: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 16:23:31,895: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 16:23:32,149: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-14 16:25:10,847: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 16:25:10,852: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 16:25:10,855: INFO: common: created directory at: artifacts]
[2024-03-14 16:25:10,857: INFO: common: created directory at: artifacts\training]
[2024-03-14 16:26:20,611: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 16:26:20,630: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 16:26:20,633: INFO: common: created directory at: artifacts]
[2024-03-14 16:26:20,635: INFO: common: created directory at: artifacts\training]
[2024-03-14 16:36:27,102: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-14 16:36:27,105: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 16:36:27,107: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 16:36:27,108: INFO: common: created directory at: artifacts]
[2024-03-14 16:36:27,108: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-14 16:36:27,109: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 16:36:31,140: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 16:36:31,188: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-14 16:36:31,188: INFO: main: *******************]
[2024-03-14 16:36:31,188: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 16:36:31,192: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 16:36:31,195: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 16:36:31,195: INFO: common: created directory at: artifacts]
[2024-03-14 16:36:31,196: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 16:36:31,975: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 16:36:33,527: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-14 16:38:07,474: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-14 16:38:07,477: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 16:38:07,481: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 16:38:07,482: INFO: common: created directory at: artifacts]
[2024-03-14 16:38:07,483: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-14 16:38:07,483: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 16:38:11,035: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 16:38:11,107: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-14 16:38:11,108: INFO: main: *******************]
[2024-03-14 16:38:11,108: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 16:38:11,112: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 16:38:11,114: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 16:38:11,115: INFO: common: created directory at: artifacts]
[2024-03-14 16:38:11,116: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 16:38:11,859: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 16:38:12,105: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-14 16:38:12,105: INFO: main: *******************]
[2024-03-14 16:38:12,105: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-14 16:38:12,106: ERROR: main: name 'ModelTrainingPipeline' is not defined]
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    model_trainer = ModelTrainingPipeline()
NameError: name 'ModelTrainingPipeline' is not defined
[2024-03-14 16:38:52,918: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-14 16:38:52,923: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 16:38:52,925: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 16:38:52,926: INFO: common: created directory at: artifacts]
[2024-03-14 16:38:52,927: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-14 16:38:52,928: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 16:38:57,066: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 16:38:57,175: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-14 16:38:57,176: INFO: main: *******************]
[2024-03-14 16:38:57,176: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 16:38:57,180: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 16:38:57,182: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 16:38:57,183: INFO: common: created directory at: artifacts]
[2024-03-14 16:38:57,183: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 16:38:57,900: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 16:38:58,155: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-14 16:38:58,155: INFO: main: *******************]
[2024-03-14 16:38:58,155: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-14 16:38:58,159: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 16:38:58,162: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 16:38:58,163: INFO: common: created directory at: artifacts]
[2024-03-14 16:38:58,163: INFO: common: created directory at: artifacts\training]
[2024-03-14 16:39:18,620: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-14 17:10:52,695: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 17:10:52,702: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 17:10:52,704: INFO: common: created directory at: artifacts]
[2024-03-14 17:11:00,199: INFO: common: json file saved at: scores.json]
[2024-03-14 17:13:25,273: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 17:13:25,279: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 17:13:25,282: INFO: common: created directory at: artifacts]
[2024-03-14 17:13:27,928: INFO: common: json file saved at: scores.json]
[2024-03-14 17:14:47,923: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 17:14:47,929: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 17:14:47,932: INFO: common: created directory at: artifacts]
[2024-03-14 17:14:50,389: INFO: common: json file saved at: scores.json]
[2024-03-15 14:49:12,433: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 14:49:12,438: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 14:49:12,961: INFO: common: created directory at: artifacts]
[2024-03-15 14:49:18,862: INFO: common: json file saved at: scores.json]
[2024-03-15 14:49:19,034: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /alimustafa0/Kidney-Disease-Classification-MLflow-DVC.mlflow/api/2.0/mlflow/runs/create]
[2024-03-15 14:49:26,648: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-03-15 14:49:31,834: INFO: builder_impl: Assets written to: C:\Users\Al-Masa\AppData\Local\Temp\tmpv723wpgn\model\data\model\assets]
[2024-03-15 15:20:39,310: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-15 15:20:39,319: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 15:20:39,324: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 15:20:39,325: INFO: common: created directory at: artifacts]
[2024-03-15 15:20:39,325: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-15 15:20:39,326: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 15:20:45,149: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 15:20:45,301: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-15 15:20:45,301: INFO: main: *******************]
[2024-03-15 15:20:45,301: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-15 15:20:45,307: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 15:20:45,310: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 15:20:45,311: INFO: common: created directory at: artifacts]
[2024-03-15 15:20:45,312: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-15 15:20:46,834: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-15 15:20:47,299: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-15 15:20:47,299: INFO: main: *******************]
[2024-03-15 15:20:47,299: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-15 15:20:47,302: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 15:20:47,308: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 15:20:47,309: INFO: common: created directory at: artifacts]
[2024-03-15 15:20:47,309: INFO: common: created directory at: artifacts\training]
[2024-03-15 15:20:55,255: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-15 15:20:55,256: INFO: main: *******************]
[2024-03-15 15:20:55,256: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-15 15:20:55,267: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 15:20:55,273: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 15:20:55,274: INFO: common: created directory at: artifacts]
[2024-03-15 15:20:58,092: INFO: common: json file saved at: scores.json]
[2024-03-15 15:20:58,093: INFO: common: json file saved at: scores.json]
[2024-03-15 15:20:58,093: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-15 15:22:32,331: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-15 15:22:32,335: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 15:22:32,344: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 15:22:32,345: INFO: common: created directory at: artifacts]
[2024-03-15 15:22:32,345: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-15 15:22:32,346: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 15:22:37,595: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 15:22:37,646: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-15 15:22:37,646: INFO: main: *******************]
[2024-03-15 15:22:37,646: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-15 15:22:37,654: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 15:22:37,656: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 15:22:37,657: INFO: common: created directory at: artifacts]
[2024-03-15 15:22:37,658: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-15 15:22:38,342: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-15 15:22:39,813: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-15 15:22:39,813: INFO: main: *******************]
[2024-03-15 15:22:39,814: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-15 15:22:39,821: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 15:22:39,824: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 15:22:39,825: INFO: common: created directory at: artifacts]
[2024-03-15 15:22:39,827: INFO: common: created directory at: artifacts\training]
[2024-03-15 15:22:54,675: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-15 15:22:54,675: INFO: main: *******************]
[2024-03-15 15:22:54,675: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-15 15:22:54,684: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 15:22:54,687: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 15:22:54,688: INFO: common: created directory at: artifacts]
[2024-03-15 15:22:57,142: INFO: common: json file saved at: scores.json]
[2024-03-15 15:22:57,143: INFO: common: json file saved at: scores.json]
[2024-03-15 15:22:57,143: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-15 15:25:38,086: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-15 15:25:38,089: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 15:25:38,102: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 15:25:38,103: INFO: common: created directory at: artifacts]
[2024-03-15 15:25:38,103: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-15 15:25:38,104: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 15:25:47,011: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 15:25:47,081: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-15 15:25:47,081: INFO: main: *******************]
[2024-03-15 15:25:47,081: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-15 15:25:47,086: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 15:25:47,088: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 15:25:47,089: INFO: common: created directory at: artifacts]
[2024-03-15 15:25:47,092: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-15 15:25:47,814: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-15 15:25:49,127: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-15 15:25:49,127: INFO: main: *******************]
[2024-03-15 15:25:49,127: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-15 15:25:49,130: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 15:25:49,132: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 15:25:49,133: INFO: common: created directory at: artifacts]
[2024-03-15 15:25:49,134: INFO: common: created directory at: artifacts\training]
[2024-03-15 15:27:28,548: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-15 15:27:28,549: INFO: main: *******************]
[2024-03-15 15:27:28,549: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-15 15:27:28,553: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 15:27:28,555: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 15:27:28,556: INFO: common: created directory at: artifacts]
[2024-03-15 15:27:30,802: INFO: common: json file saved at: scores.json]
[2024-03-15 15:27:30,803: INFO: common: json file saved at: scores.json]
[2024-03-15 15:27:30,804: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-15 15:32:15,976: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-15 15:32:15,982: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 15:32:15,991: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 15:32:15,992: INFO: common: created directory at: artifacts]
[2024-03-15 15:32:15,992: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-15 15:32:15,993: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 15:32:24,891: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 15:32:24,960: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-15 15:32:24,961: INFO: main: *******************]
[2024-03-15 15:32:24,961: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-15 15:32:24,964: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 15:32:24,966: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 15:32:24,967: INFO: common: created directory at: artifacts]
[2024-03-15 15:32:24,967: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-15 15:32:26,164: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-15 15:32:26,957: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-15 15:32:26,958: INFO: main: *******************]
[2024-03-15 15:32:26,958: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-15 15:32:26,961: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 15:32:26,963: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 15:32:26,964: INFO: common: created directory at: artifacts]
[2024-03-15 15:32:26,964: INFO: common: created directory at: artifacts\training]
[2024-03-15 15:32:39,587: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-15 15:32:39,587: INFO: main: *******************]
[2024-03-15 15:32:39,587: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-15 15:32:39,590: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 15:32:39,592: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 15:32:39,593: INFO: common: created directory at: artifacts]
[2024-03-15 15:32:41,848: INFO: common: json file saved at: scores.json]
[2024-03-15 15:32:41,850: INFO: common: json file saved at: scores.json]
[2024-03-15 15:32:43,944: ERROR: main: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    model_evalution.main()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 60, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}
[2024-03-15 16:14:07,998: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-15 16:14:08,029: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:14:08,044: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:14:08,051: INFO: common: created directory at: artifacts]
[2024-03-15 16:14:08,052: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-15 16:14:08,052: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 16:14:13,460: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 16:14:13,633: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-15 16:14:13,633: INFO: main: *******************]
[2024-03-15 16:14:13,634: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-15 16:14:13,637: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:14:13,639: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:14:13,639: INFO: common: created directory at: artifacts]
[2024-03-15 16:14:13,650: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-15 16:14:16,257: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-15 16:14:17,221: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-15 16:14:17,221: INFO: main: *******************]
[2024-03-15 16:14:17,221: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-15 16:14:17,224: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:14:17,226: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:14:17,227: INFO: common: created directory at: artifacts]
[2024-03-15 16:14:17,227: INFO: common: created directory at: artifacts\training]
[2024-03-15 16:15:43,402: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-15 16:15:43,403: INFO: main: *******************]
[2024-03-15 16:15:43,403: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-15 16:15:43,407: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:15:43,409: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:15:43,410: INFO: common: created directory at: artifacts]
[2024-03-15 16:15:45,766: INFO: common: json file saved at: scores.json]
[2024-03-15 16:15:45,768: INFO: common: json file saved at: scores.json]
[2024-03-15 16:15:47,778: ERROR: main: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    model_evalution.main()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 60, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}
[2024-03-15 16:31:44,775: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-15 16:31:44,779: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:31:44,782: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:31:44,782: INFO: common: created directory at: artifacts]
[2024-03-15 16:31:44,782: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-15 16:31:44,784: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 16:31:48,908: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 16:31:48,998: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-15 16:31:48,999: INFO: main: *******************]
[2024-03-15 16:31:48,999: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-15 16:31:49,002: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:31:49,005: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:31:49,006: INFO: common: created directory at: artifacts]
[2024-03-15 16:31:49,006: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-15 16:31:49,739: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-15 16:31:51,299: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-15 16:31:51,300: INFO: main: *******************]
[2024-03-15 16:31:51,300: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-15 16:31:51,305: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:31:51,308: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:31:51,308: INFO: common: created directory at: artifacts]
[2024-03-15 16:31:51,309: INFO: common: created directory at: artifacts\training]
[2024-03-15 16:31:58,533: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-15 16:31:58,534: INFO: main: *******************]
[2024-03-15 16:31:58,534: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-15 16:31:58,540: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:31:58,544: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:31:58,545: INFO: common: created directory at: artifacts]
[2024-03-15 16:32:00,754: INFO: common: json file saved at: scores.json]
[2024-03-15 16:32:00,755: INFO: common: json file saved at: scores.json]
[2024-03-15 16:32:02,202: ERROR: main: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    model_evalution.main()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 64, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}
[2024-03-15 16:33:27,642: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-15 16:33:27,646: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:33:27,648: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:33:27,648: INFO: common: created directory at: artifacts]
[2024-03-15 16:33:27,649: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-15 16:33:27,649: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 16:33:33,264: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 16:33:33,315: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-15 16:33:33,316: INFO: main: *******************]
[2024-03-15 16:33:33,316: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-15 16:33:33,321: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:33:33,324: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:33:33,325: INFO: common: created directory at: artifacts]
[2024-03-15 16:33:33,325: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-15 16:33:33,930: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-15 16:33:35,300: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-15 16:33:35,301: INFO: main: *******************]
[2024-03-15 16:33:35,301: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-15 16:33:35,306: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:33:35,309: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:33:35,309: INFO: common: created directory at: artifacts]
[2024-03-15 16:33:35,310: INFO: common: created directory at: artifacts\training]
[2024-03-15 16:33:41,296: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-15 16:33:41,297: INFO: main: *******************]
[2024-03-15 16:33:41,297: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-15 16:33:41,305: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:33:41,310: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:33:41,311: INFO: common: created directory at: artifacts]
[2024-03-15 16:33:43,487: INFO: common: json file saved at: scores.json]
[2024-03-15 16:33:43,488: INFO: common: json file saved at: scores.json]
[2024-03-15 16:33:45,073: ERROR: main: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    model_evalution.main()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 60, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}
[2024-03-15 16:36:23,282: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-15 16:36:23,285: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:36:23,287: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:36:23,288: INFO: common: created directory at: artifacts]
[2024-03-15 16:36:23,288: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-15 16:36:23,289: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 16:36:28,700: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 16:36:28,765: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-15 16:36:28,765: INFO: main: *******************]
[2024-03-15 16:36:28,765: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-15 16:36:28,770: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:36:28,774: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:36:28,775: INFO: common: created directory at: artifacts]
[2024-03-15 16:36:28,776: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-15 16:36:29,384: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-15 16:36:30,778: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-15 16:36:30,778: INFO: main: *******************]
[2024-03-15 16:36:30,779: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-15 16:36:30,782: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:36:30,784: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:36:30,784: INFO: common: created directory at: artifacts]
[2024-03-15 16:36:30,785: INFO: common: created directory at: artifacts\training]
[2024-03-15 16:36:36,532: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-15 16:36:36,532: INFO: main: *******************]
[2024-03-15 16:36:36,533: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-15 16:36:36,537: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:36:36,541: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:36:36,541: INFO: common: created directory at: artifacts]
[2024-03-15 16:36:38,724: INFO: common: json file saved at: scores.json]
[2024-03-15 16:36:38,725: INFO: common: json file saved at: scores.json]
[2024-03-15 16:36:40,600: ERROR: main: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    model_evalution.main()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 62, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}
[2024-03-15 16:40:53,676: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-15 16:40:53,679: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:40:53,682: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:40:53,682: INFO: common: created directory at: artifacts]
[2024-03-15 16:40:53,683: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-15 16:40:53,683: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 16:40:59,024: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 16:40:59,089: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-15 16:40:59,090: INFO: main: *******************]
[2024-03-15 16:40:59,090: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-15 16:40:59,093: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:40:59,096: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:40:59,096: INFO: common: created directory at: artifacts]
[2024-03-15 16:40:59,097: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-15 16:40:59,696: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-15 16:41:01,054: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-15 16:41:01,055: INFO: main: *******************]
[2024-03-15 16:41:01,055: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-15 16:41:01,058: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:41:01,060: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:41:01,060: INFO: common: created directory at: artifacts]
[2024-03-15 16:41:01,061: INFO: common: created directory at: artifacts\training]
[2024-03-15 16:41:06,936: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-15 16:41:06,936: INFO: main: *******************]
[2024-03-15 16:41:06,937: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-15 16:41:06,943: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:41:06,947: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:41:06,948: INFO: common: created directory at: artifacts]
[2024-03-15 16:41:09,237: INFO: common: json file saved at: scores.json]
[2024-03-15 16:41:09,238: INFO: common: json file saved at: scores.json]
[2024-03-15 16:41:10,826: ERROR: main: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    model_evalution.main()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 63, in log_into_mlflow
    mlflow.start_run()
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}
[2024-03-15 16:42:18,002: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-15 16:42:18,006: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:42:18,008: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:42:18,008: INFO: common: created directory at: artifacts]
[2024-03-15 16:42:18,009: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-15 16:42:18,009: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 16:42:21,488: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 16:42:21,554: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-15 16:42:21,555: INFO: main: *******************]
[2024-03-15 16:42:21,555: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-15 16:42:21,560: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:42:21,563: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:42:21,563: INFO: common: created directory at: artifacts]
[2024-03-15 16:42:21,564: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-15 16:42:22,357: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-15 16:42:24,004: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-15 16:42:24,004: INFO: main: *******************]
[2024-03-15 16:42:24,004: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-15 16:42:24,007: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:42:24,009: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:42:24,009: INFO: common: created directory at: artifacts]
[2024-03-15 16:42:24,010: INFO: common: created directory at: artifacts\training]
[2024-03-15 16:42:29,717: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-15 16:42:29,717: INFO: main: *******************]
[2024-03-15 16:42:29,718: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-15 16:42:29,722: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:42:29,725: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:42:29,726: INFO: common: created directory at: artifacts]
[2024-03-15 16:42:31,927: INFO: common: json file saved at: scores.json]
[2024-03-15 16:42:31,928: INFO: common: json file saved at: scores.json]
[2024-03-15 16:42:31,929: ERROR: main: 'NoneType' object has no attribute 'info']
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    model_evalution.main()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 65, in log_into_mlflow
    print(f"Active run_id: {run.info.run_id}")
AttributeError: 'NoneType' object has no attribute 'info'
[2024-03-15 16:59:48,898: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /alimustafa0/Kidney-Disease-Classification-MLflow-DVC.mlflow/api/2.0/mlflow/runs/create]
[2024-03-15 17:04:24,872: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 17:04:24,888: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 17:04:24,890: INFO: common: created directory at: artifacts]
[2024-03-15 17:04:27,986: INFO: common: json file saved at: scores.json]
[2024-03-15 17:09:10,990: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-15 17:09:10,993: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 17:09:10,996: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 17:09:11,012: INFO: common: created directory at: artifacts]
[2024-03-15 17:09:11,013: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-15 17:09:11,013: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 17:09:14,899: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 17:09:14,956: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-15 17:09:14,956: INFO: main: *******************]
[2024-03-15 17:09:14,957: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-15 17:09:14,962: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 17:09:14,964: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 17:09:14,965: INFO: common: created directory at: artifacts]
[2024-03-15 17:09:14,965: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-15 17:09:16,074: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-15 17:09:16,376: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-15 17:09:16,376: INFO: main: *******************]
[2024-03-15 17:09:16,377: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-15 17:09:16,380: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 17:09:16,382: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 17:09:16,382: INFO: common: created directory at: artifacts]
[2024-03-15 17:09:16,383: INFO: common: created directory at: artifacts\training]
[2024-03-15 17:10:45,400: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-15 17:10:45,400: INFO: main: *******************]
[2024-03-15 17:10:45,400: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-15 17:10:45,403: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 17:10:45,405: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 17:10:45,406: INFO: common: created directory at: artifacts]
[2024-03-15 17:10:47,695: INFO: common: json file saved at: scores.json]
[2024-03-15 17:10:47,696: INFO: common: json file saved at: scores.json]
[2024-03-15 17:10:47,697: ERROR: main: 'NoneType' object has no attribute 'info']
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    model_evalution.main()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 65, in log_into_mlflow
    print(f"Active run_id: {run.info.run_id}")
AttributeError: 'NoneType' object has no attribute 'info'
[2024-03-15 17:15:05,615: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-15 17:15:05,619: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 17:15:05,621: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 17:15:05,622: INFO: common: created directory at: artifacts]
[2024-03-15 17:15:05,623: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-15 17:15:05,623: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 17:15:10,014: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 17:15:10,068: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-15 17:15:10,068: INFO: main: *******************]
[2024-03-15 17:15:10,068: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-15 17:15:10,073: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 17:15:10,076: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 17:15:10,077: INFO: common: created directory at: artifacts]
[2024-03-15 17:15:10,077: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-15 17:15:10,816: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-15 17:15:12,160: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-15 17:15:12,160: INFO: main: *******************]
[2024-03-15 17:15:12,160: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-15 17:15:12,164: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 17:15:12,166: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 17:15:12,167: INFO: common: created directory at: artifacts]
[2024-03-15 17:15:12,167: INFO: common: created directory at: artifacts\training]
[2024-03-15 17:16:35,542: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-15 17:16:35,543: INFO: main: *******************]
[2024-03-15 17:16:35,544: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-15 17:16:35,553: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 17:16:35,561: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 17:16:35,562: INFO: common: created directory at: artifacts]
[2024-03-15 17:16:37,761: INFO: common: json file saved at: scores.json]
[2024-03-15 17:16:37,762: INFO: common: json file saved at: scores.json]
[2024-03-15 17:16:39,416: ERROR: main: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    model_evalution.main()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 60, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}
[2024-03-15 17:21:06,668: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-15 17:21:06,671: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 17:21:06,681: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 17:21:06,682: INFO: common: created directory at: artifacts]
[2024-03-15 17:21:06,683: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-15 17:21:06,683: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 17:21:12,514: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 17:21:12,577: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-15 17:21:12,577: INFO: main: *******************]
[2024-03-15 17:21:12,578: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-15 17:21:12,583: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 17:21:12,586: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 17:21:12,587: INFO: common: created directory at: artifacts]
[2024-03-15 17:21:12,587: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-15 17:21:13,184: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-15 17:21:14,459: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-15 17:21:14,460: INFO: main: *******************]
[2024-03-15 17:21:14,461: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-15 17:21:14,467: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 17:21:14,471: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 17:21:14,472: INFO: common: created directory at: artifacts]
[2024-03-15 17:21:14,473: INFO: common: created directory at: artifacts\training]
[2024-03-15 17:21:20,830: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-15 17:21:20,831: INFO: main: *******************]
[2024-03-15 17:21:20,832: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-15 17:21:20,841: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 17:21:20,850: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 17:21:20,851: INFO: common: created directory at: artifacts]
[2024-03-15 17:21:23,038: INFO: common: json file saved at: scores.json]
[2024-03-15 17:21:23,039: INFO: common: json file saved at: scores.json]
[2024-03-15 17:21:24,778: ERROR: main: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    model_evalution.main()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 66, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}
[2024-03-15 17:25:28,040: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /alimustafa0/Kidney-Disease-Classification-MLflow-DVC.mlflow/api/2.0/mlflow/runs/create]
[2024-03-15 17:29:47,934: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-15 17:29:47,938: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 17:29:47,940: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 17:29:47,941: INFO: common: created directory at: artifacts]
[2024-03-15 17:29:47,941: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-15 17:29:47,941: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 17:29:51,611: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 17:29:51,659: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-15 17:29:51,660: INFO: main: *******************]
[2024-03-15 17:29:51,660: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-15 17:29:51,664: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 17:29:51,666: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 17:29:51,667: INFO: common: created directory at: artifacts]
[2024-03-15 17:29:51,667: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-15 17:29:52,498: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-15 17:29:53,617: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-15 17:29:53,617: INFO: main: *******************]
[2024-03-15 17:29:53,617: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-15 17:29:53,620: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 17:29:53,622: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 17:29:53,623: INFO: common: created directory at: artifacts]
[2024-03-15 17:29:53,623: INFO: common: created directory at: artifacts\training]
[2024-03-15 17:29:59,823: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-15 17:29:59,824: INFO: main: *******************]
[2024-03-15 17:29:59,824: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-15 17:29:59,830: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 17:29:59,833: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 17:29:59,834: INFO: common: created directory at: artifacts]
[2024-03-15 17:30:02,123: INFO: common: json file saved at: scores.json]
[2024-03-15 17:30:02,124: INFO: common: json file saved at: scores.json]
[2024-03-15 17:30:06,173: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-03-15 17:30:08,086: INFO: builder_impl: Assets written to: C:\Users\Al-Masa\AppData\Local\Temp\tmpfvfq_kgo\model\data\model\assets]
[2024-03-15 17:33:45,543: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-15 17:35:03,983: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-15 17:35:03,986: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 17:35:03,989: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 17:35:03,990: INFO: common: created directory at: artifacts]
[2024-03-15 17:35:03,991: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-15 17:35:03,991: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 17:35:09,352: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-15 17:35:09,404: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-15 17:35:09,404: INFO: main: *******************]
[2024-03-15 17:35:09,404: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-15 17:35:09,409: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 17:35:09,414: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 17:35:09,414: INFO: common: created directory at: artifacts]
[2024-03-15 17:35:09,415: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-15 17:35:10,225: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-15 17:35:12,049: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-15 17:35:12,050: INFO: main: *******************]
[2024-03-15 17:35:12,050: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-15 17:35:12,053: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 17:35:12,055: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 17:35:12,055: INFO: common: created directory at: artifacts]
[2024-03-15 17:35:12,056: INFO: common: created directory at: artifacts\training]
[2024-03-15 17:36:52,465: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-15 17:36:52,466: INFO: main: *******************]
[2024-03-15 17:36:52,466: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-15 17:36:52,472: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 17:36:52,475: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 17:36:52,476: INFO: common: created directory at: artifacts]
[2024-03-15 17:36:55,376: INFO: common: json file saved at: scores.json]
[2024-03-15 17:36:55,377: INFO: common: json file saved at: scores.json]
[2024-03-15 17:36:59,837: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-03-15 17:37:01,566: INFO: builder_impl: Assets written to: C:\Users\Al-Masa\AppData\Local\Temp\tmpw5o0c7mm\model\data\model\assets]
[2024-03-15 17:40:17,126: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-16 14:44:55,440: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-16 14:44:55,444: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-16 14:44:55,446: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-16 14:44:55,446: INFO: common: created directory at: artifacts]
[2024-03-16 14:44:55,447: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-16 14:44:55,447: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-16 14:45:00,457: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/105a9IWhafFMxSpFkseQiWDo_X0Ny5020/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-16 14:45:00,514: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-16 14:45:33,217: INFO: stage_02_prepare_base_model: *******************]
[2024-03-16 14:45:33,217: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-16 14:45:33,221: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-16 14:45:33,225: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-16 14:45:33,226: INFO: common: created directory at: artifacts]
[2024-03-16 14:45:33,226: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-16 14:45:34,186: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-16 14:45:34,577: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-16 14:45:47,731: INFO: stage_03_model_training: *******************]
[2024-03-16 14:45:47,731: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-03-16 14:45:47,734: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-16 14:45:47,737: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-16 14:45:47,738: INFO: common: created directory at: artifacts]
[2024-03-16 14:45:47,738: INFO: common: created directory at: artifacts\training]
[2024-03-16 14:45:55,213: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-16 14:46:13,422: INFO: stage_04_model_evaluation: *******************]
[2024-03-16 14:46:13,422: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-16 14:46:13,425: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-16 14:46:13,427: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-16 14:46:13,428: INFO: common: created directory at: artifacts]
[2024-03-16 14:46:16,663: INFO: common: json file saved at: scores.json]
[2024-03-16 14:46:16,664: INFO: common: json file saved at: scores.json]
[2024-03-16 14:46:16,665: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-16 15:16:00,845: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.19:8080]
[2024-03-16 15:16:00,845: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-16 15:16:29,154: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 15:16:29] "GET / HTTP/1.1" 200 -]
[2024-03-16 15:16:56,823: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-03-16 15:16:56,840: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 15:16:56] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-16 15:18:02,992: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 15:18:02] "GET / HTTP/1.1" 200 -]
[2024-03-16 15:19:50,527: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.19:8080]
[2024-03-16 15:19:50,527: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-16 15:20:00,656: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 15:20:00] "GET / HTTP/1.1" 200 -]
[2024-03-16 15:20:05,512: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("training", "model.h5"))
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at training\model.h5
[2024-03-16 15:20:05,518: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 15:20:05] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-16 15:20:40,085: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 15:20:40] "GET / HTTP/1.1" 200 -]
[2024-03-16 15:20:59,830: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\al-masa\desktop\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("training", "model.h5"))
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Al-Masa\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at training\model.h5
[2024-03-16 15:20:59,831: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 15:20:59] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-16 15:23:32,621: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.19:8080]
[2024-03-16 15:23:32,621: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-16 15:23:37,073: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 15:23:37] "GET / HTTP/1.1" 200 -]
[2024-03-16 15:23:44,248: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 15:23:44] "POST /predict HTTP/1.1" 200 -]
[2024-03-16 15:24:06,316: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 15:24:06] "POST /predict HTTP/1.1" 200 -]
[2024-03-16 15:24:16,975: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 15:24:16] "POST /predict HTTP/1.1" 200 -]
[2024-03-16 15:34:14,728: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.19:8080]
[2024-03-16 15:34:14,728: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-16 15:34:20,243: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 15:34:20] "GET / HTTP/1.1" 200 -]
[2024-03-16 15:34:28,076: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 15:34:28] "POST /predict HTTP/1.1" 200 -]
[2024-03-16 17:16:25,450: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.19:8080]
[2024-03-16 17:16:25,450: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-16 17:16:33,793: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 17:16:33] "GET / HTTP/1.1" 200 -]
[2024-03-16 17:16:34,025: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 17:16:34] "[33mGET /Sharawy%20Brand.png HTTP/1.1[0m" 404 -]
[2024-03-16 17:17:00,955: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 17:17:00] "[33mGET /Sharawy%20Brand.png HTTP/1.1[0m" 404 -]
